# .goreleaser.yml
# Build and release gcool binaries

project_name: gcool
env:
  - GO111MODULE=on

builds:
  - id: gcool
    main: ./main.go
    binary: gcool
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - '7'
    ldflags:
      - -s -w

archives:
  - id: gcool-archive
    builds:
      - gcool
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

release:
  github:
    owner: coollabsio
    name: gcool
  prerelease: auto
  draft: false
  make_latest: true

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))?!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\(.+\))?!?:.+$'
      order: 1
    - title: Others
      order: 999
