# .goreleaser.yml
# Build and release jean binaries

project_name: jean
env:
  - GO111MODULE=on

builds:
  - id: jean
    main: ./main.go
    binary: jean
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - '7'
    ldflags:
      - -s -w

archives:
  - id: jean-archive
    builds:
      - jean
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: coollabsio
    name: jean
  prerelease: auto
  draft: false
  make_latest: true

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))?!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\(.+\))?!?:.+$'
      order: 1
    - title: Others
      order: 999
